### ISSUE TITLE
Alternative storage location?

### ISSUE THREAD

**Issue by minz1027** [screwdriver-cd/job-tools#14]
Should we be storing the launcher somewhere else?  The problem with Docker containers is we need to start this as a volume container (daemon mode), then mount it to the actual build container (non daemon mode).  When the build ends, we need to kill the data container.

**Comment by stjohnjohnson** [comment]
@jer What do you think?  Right now, I can't think of a one(or two) line command we can run that does the following:
 - Starts the build container with the launcher mounted at `/opt/screwdriver`
 - When the launcher exits, clean up everything

**Comment by jer** [comment]
When you say "clean up everything" are you wanting it to clean up the volume container too? We can do it with docker-compose with something like this:

```yaml
Job-Tools:
  image: screwdriver-cd/job-tools:latest
  entrypoint: /bin/init

Build-12345:
  image: golang
  volumes_from:
    - Job-Tools
```

I think  you can do the same thing with multiple docker commands too. ie, use an exited container as a volume mount. Haven't tried that though.
